@extends('legal.layout')
@section('title', 'Terms of Service — SEOKRU Analytics')
@section('description', 'Terms of Service for SEOKRU Analytics.')

@section('content')

<h1>Terms of Service</h1>
<p class="meta">Last updated: April 23, 2026</p>

<p>These Terms govern your use of SEOKRU Analytics (the "Service"), a free pilot tool operated by SEOKRU that connects to your Google Analytics 4 and Google Search Console accounts to generate plain-English reports.</p>

<h2>1. Acceptance</h2>
<p>By signing in with your Google account and using the Service, you agree to these Terms and to our <a href="/privacy">Privacy Policy</a>. If you do not agree, do not use the Service.</p>

<h2>2. The Service</h2>
<p>The Service reads data from your GA4 and GSC accounts (with your explicit OAuth consent) and generates readable reports. It is provided as a free pilot, primarily for evaluation and feedback purposes. Features, availability, and limits may change without notice during the pilot.</p>

<h2>3. Eligibility</h2>
<ul>
<li>You must be 13 or older</li>
<li>You must have authority to grant access to the Google properties you connect</li>
<li>You must comply with Google's Terms of Service for GA4 and Search Console</li>
</ul>

<h2>4. Acceptable use</h2>
<p>You agree not to:</p>
<ul>
<li>Reverse-engineer, decompile, or attempt to extract source code from the Service</li>
<li>Use the Service to access data you are not authorized to view</li>
<li>Abuse Google APIs via the Service (e.g., running queries solely to circumvent rate limits for unrelated purposes)</li>
<li>Use the Service to harass, defame, or violate the rights of others</li>
<li>Use automated means to scrape or replicate the Service beyond reasonable personal or business use</li>
</ul>

<h2>5. Your content and data</h2>
<p>You retain ownership of all data in your Google accounts and all reports generated for you. By using the Service, you grant us a limited license to process your data solely to operate the Service as described in the <a href="/privacy">Privacy Policy</a>.</p>

<h2>6. No warranty</h2>
<p>The Service is provided "as is" and "as available", without warranties of any kind, express or implied. We do not guarantee accuracy, completeness, or fitness for any particular purpose. Reports generated by the Service include narrative text produced by AI models and may contain errors; always verify critical numbers against the source Google tools before making business decisions.</p>

<h2>7. Limitation of liability</h2>
<p>To the maximum extent permitted by law, SEOKRU and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service. Our total aggregate liability for any claim shall not exceed fifty US dollars (USD 50) or the amount you paid us in the twelve months preceding the claim, whichever is greater.</p>

<h2>8. Third-party services</h2>
<p>The Service depends on third-party APIs (Google, Groq, Gemini) whose terms and availability are outside our control. Interruptions or changes to those services may affect the Service.</p>

<h2>9. Termination</h2>
<p>You may stop using the Service at any time by disconnecting your Google account (see Privacy Policy §6). We may suspend or terminate access for violations of these Terms, for abuse, or when the pilot ends.</p>

<h2>10. Changes</h2>
<p>We may update these Terms. Material changes will be posted on this page with a new "Last updated" date. Continued use after changes constitutes acceptance.</p>

<h2>11. Governing law</h2>
<p>These Terms are governed by the laws of the State of Israel, without regard to conflict-of-laws principles. Disputes shall be resolved in the competent courts of Tel Aviv, Israel.</p>

<h2>12. Contact</h2>
<p>Questions: <a href="mailto:info@seokru.com">info@seokru.com</a></p>

@endsection
